### ISSUE TITLE
Add support for uppercase `SELECT CURRENT_SCHEMA()`

### ISSUE THREAD

**Issue by alethenorio** [GoogleCloudPlatform/pgadapter#2326]
[golang-migrate](http://github.com/golang-migrate/migrate) currently [uses](https://github.com/golang-migrate/migrate/blob/555501f7cdbf52a34bf66d49eb37eb72b22b2a85/database/postgres/postgres.go#L92) the query `SELECT CURRENT_SCHEMA()` (all uppercase) but this is not supported by pgadapter since it looks for [very specific](https://github.com/GoogleCloudPlatform/pgadapter/blob/cc6c767261fd6dc887c2a7dda2bc5e2d04a37228/src/main/java/com/google/cloud/spanner/pgadapter/statements/local/SelectCurrentSchemaStatement.java#L35-L48) combinations (none of them with uppercase `CURRENT_SCHEMA`.

Could we add support for that? Not creating a PR as you are not accepting external contributions at the moment otherwise I'd be happy to do so.

**Comment by olavloite** [comment]
@alethenorio I've added a sample for how to use Golang Migrate with PGAdapter here: https://github.com/GoogleCloudPlatform/pgadapter/tree/postgresql-dialect/samples/golang/migrate

Note that you need to manually include the name of the application `golang-migrate` in the connection string. Otherwise, PGAdapter does not know what to do with the `select pg_advisory_lock($1)` statements that Golang Migrate also executes.
