### ISSUE TITLE
Compatibility Issue with Prisma ORM

### ISSUE THREAD

**Issue by NOT-HAL9000** [GoogleCloudPlatform/pgadapter#581]
Trying to see if Prisma can be used with PGAdapter and Cloud Spanner. Getting the following error. Trying to understand if this is a Prisma or PGAdapter problem. Thanks! 

```Error querying the database: db error: ERROR: Invalid SET statement: SET NAMES 'UTF8'. Expected TO or =.```

Referenced Discussion and reproducibility steps on Prisma Repo here: https://github.com/prisma/prisma/issues/717#issuecomment-1378039892

**Comment by olavloite** [comment]
Thanks for reaching out. We have not yet tested Prisma with PGAdapter, so we can't make any statements on how well/bad it will work with Prisma.

This specific issue however is a PGAdapter problem. The `SET NAMES 'UTF8'` syntax is not a standard PostgreSQL statement, but it is something that PostgreSQL apparently has added support for to adhere to the ANSI SQL standard. See https://www.postgresql.org/docs/current/multibyte.html. PGAdapter currently does not take that possibility into account.

**Comment by NOT-HAL9000** [comment]
Thanks for the response. 

I wasn't aware of this and had wrongly assumed that Prisma may have been accidentally sending mysql commands based on some quick google searches. 

I noticed this project doesn't accept pull requests. Could I submit compatibility with Prisma as a feature request?

**Comment by olavloite** [comment]
> I noticed this project doesn't accept pull requests.

Hmm.... Maybe it's time to update that part of the documentation. Let me check with a couple of other people as well.

> Could I submit compatibility with Prisma as a feature request?

Certainly!

**Comment by NOT-HAL9000** [comment]
> Certainly!

Would love to see a popular type-safe typescript ORM get Spanner compatibility! 

---

FYI, I tried ```SET NAMES 'UTF8'``` in both the DDL and Query editors and both returned an error. I'm not sure if this is because the spanner console runs a PGAdapter in the background which fails for the same reason. 

DDL Editor: 
<img width="546" alt="Screen Shot 2023-01-12 at 12 58 03 am" src="https://user-images.githubusercontent.com/70297791/211824817-3c8430e5-552a-4731-9b1b-1558826e691a.png">

QUERY Editor:
<img width="488" alt="Screen Shot 2023-01-12 at 12 56 36 am" src="https://user-images.githubusercontent.com/70297791/211824878-8aa6dda8-21a5-4f2d-b4f7-6dfa9ed5bb0c.png">

**Comment by janpio** [comment]
Hey, Prisma here 👋 

Amazing to see this issue, and how @NOT-HAL9000 is pushing forward to figure out what is standing in the way of Prisma and Google Cloud Spanner (via PgAdapter) to work together (they mentioned it in our issue https://github.com/prisma/prisma/issues/717#issuecomment-1378039892).

Might it be as simple as accepting `SET NAME 'UTF8'` in the adapter and swallowing it instead of forwarding it (for now)?

As we are currently basically just trying to find the _real_ blockers down the line (which probably will be other, not supported queries), if someone (*hint @NOT-HAL9000 *hint 😆) opens a PR is there a simple way to test that code/adapter locally?

**Comment by olavloite** [comment]
@NOT-HAL9000 I've created #589 for the more generic request to add support for Prisma, so we can treat this issue as a specific issue with the `set names ...` statement.
