### ISSUE TITLE
use of the default application credentials in a k8s deployment with workload identity

### ISSUE THREAD

**Issue by mvanholsteijn** [GoogleCloudPlatform/pgadapter#6]
The Adapter requires you to specify a credentials file, but I would prefer not to create a file and have the adapter use the default credentials provided by GKE workload identity.

**Comment by Vizerai** [comment]
This should work if you set the GOOGLE_APPLICATION_CREDENTIALS environment variable:

export GOOGLE_APPLICATION_CREDENTIALS=\<path to credentials\>

**Comment by mvanholsteijn** [comment]
That still requires a json  key crendential to be generated and placed inside the container. I prefer to use the workload identity.

**Comment by eriksw** [comment]
I want to use this but making service account keys is a non-starter (org policy enforced).

This tool needs to support the normal Application Default Credentials loading process common to every other Google Cloud client/sdk library.

**Comment by olavloite** [comment]
@eriksw @mvanholsteijn The latest version should now pick up any default application credentials of the environment that it is running when no credentials have been specified in the startup parameters of PGAdapter: https://github.com/GoogleCloudPlatform/pgadapter/blob/20754db9266f51af3b44fbb41137d12b1e551b3c/src/main/java/com/google/cloud/spanner/pgadapter/metadata/OptionsMetadata.java#L191

Please let me know by reopening the issue if that does not solve your issue.

Sorry that a reference to this issue was not in included in the commit that fixed it. The fix was included in a larger PR and went under the radar.

**Comment by mvanholsteijn** [comment]
super nice!
