### ISSUE TITLE
connect to spanner emulator

### ISSUE THREAD

**Issue by zhangk430** [GoogleCloudPlatform/pgadapter#793]
Hello, may I ask how can I use pgadapter to connect to cloud spanner emulator?
To run pgadapter it requires -c to a credential file. But for spanner emulator I believe there is no credential for it.

**Comment by olavloite** [comment]
@zhangk430 Thanks for reaching out. There are a couple of things that are different when connecting to the emulator:
1. As you noted: You should not supply any credentials.
2. You need to use a different endpoint.
3. You need to use plain text instead of SSL.

PGAdapter uses the same engine as the Cloud Spanner JDBC driver, and that engine supports a flag to automatically configure a connection to the emulator. You can pass any JDBC connection property to PGAdapter using the `-r` flag. So connecting to the emulator would look like this:

```
wget https://storage.googleapis.com/pgadapter-jar-releases/pgadapter.tar.gz \
  && tar -xzvf pgadapter.tar.gz
java -jar pgadapter.jar \
  -p my-project -i my-instance -d my-database \
  -r autoConfigEmulator=true
```

The advantage of using the above flag is that it will also automatically create the instance and database that you are referencing on the emulator, without you first needing to create them.

The above is equivalent to:

```
wget https://storage.googleapis.com/pgadapter-jar-releases/pgadapter.tar.gz \
  && tar -xzvf pgadapter.tar.gz
java -jar pgadapter.jar \
  -p my-project -i my-instance -d my-database \
  -e localhost:9010 -c="" \
  -r usePlainText=true
```

__BUT__: Currently, the emulator does not support the PostgreSQL dialect, and PGAdapter can only be used to connect to PostgreSQL databases. It is therefore not possible to use PGAdapter with emulator at this time. If you try to do the above and then connect to PGAdapter, you will get an error saying that PGAdapter only supports `GOOGLE_STANDARD_SQL` databases.

Note: The above examples use the Java build instead of the Docker container for PGAdapter. The reason for that is that if you run PGAdapter in a Docker container, it will not automatically be able to access the emulator running on your local host.

**Comment by olavloite** [comment]
We've released support for PostgreSQL dialect databases in version [1.5.12 of the Emulator](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.12). Version 0.26.0 and higher of PGAdapter also supports connecting to the emulator.

This [documentation page](https://github.com/GoogleCloudPlatform/pgadapter/blob/postgresql-dialect/docs/emulator.md) shows you how you can connect PGAdapter to the emulator.

**Comment by olavloite** [comment]
We now also have a pre-built Docker image that contains both PGAdapter and the Emulator:

```
docker pull gcr.io/cloud-spanner-pg-adapter/pgadapter-emulator
docker run \
  -d -p 5432:5432 \
  gcr.io/cloud-spanner-pg-adapter/pgadapter-emulator
sleep 2
psql -h localhost -p 5432 -d test-database
```
